service: entity-payroll-setting

provider:
  name: aws
  runtime: nodejs12.x
  apiGateway:
    shouldStartNameWithService: true
  stage: dev
  releasedVersion: v1
  stackName: ${self:service}-${self:provider.stage}
  region: ap-southeast-1 # this is the region that we deploy our lambda to
  environment:
    item_table: 'Entity'
  iamRoleStatements:
    - Effect: "Allow" # or Deny
      Resource: "*"
      Action: # this is the action against dynamodb
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchWriteItem"
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
plugins:
  - serverless-domain-manager

custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: apis.banhji.com
    staging: staging-apis.banhji.com
    dev: dev-apis.banhji.com
  customDomain:
    basePath: "${self:service}"
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: "${self:custom.stage}"
    createRout53Record: true
functions:
  payroll-bank-create:
    handler: api/payroll-setting/add_bank.index
    events:
      - http:
          path: bank/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-bank-get:
    handler: api/payroll-setting/get_bank.get
    events:
      - http:
          path: bank/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-tax-create:
    handler: api/payroll-setting/add_tax.index
    events:
      - http:
          path: tax/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-tax-get:
    handler: api/payroll-setting/get_tax.get
    events:
      - http:
          path: tax/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-branch-create:
    handler: api/payroll-setting/add_department.index
    events:
      - http:
          path: department/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-branch-get:
    handler: api/payroll-setting/get_department.get
    events:
      - http:
          path: department/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-position-create:
    handler: api/payroll-setting/add_position.index
    events:
      - http:
          path: position/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-position-get:
    handler: api/payroll-setting/get_position.get
    events:
      - http:
          path: position/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-conponent-create:
    handler: api/payroll-setting/add_pay_component.index
    events:
      - http:
          path: pay-component/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-conponent-get:
    handler: api/payroll-setting/get_pay_component.get
    events:
      - http:
          path: pay-component/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-period-create:
    handler: api/payroll-setting/add_period.index
    events:
      - http:
          path: period/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-period-get:
    handler: api/payroll-setting/get_period.get
    events:
      - http:
          path: period/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-nssf-create:
    handler: api/payroll-setting/add_nssf.index
    events:
      - http:
          path: nssf/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                id: true
  payroll-nssf-get:
    handler: api/payroll-setting/get_nssf.get
    events:
      - http:
          path: nssf/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: true
  type-of-work-create:
    handler: api/payroll-setting/add_type_of_work.index
    events:
      - http:
          path: type-of-work/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                id: true
  type-of-work-get:
    handler: api/payroll-setting/get_type_of_work.get
    events:
      - http:
          path: type-of-work/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: true
  specific-work-create:
    handler: api/payroll-setting/add_specific_work.index
    events:
      - http:
          path: specific-work/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                id: true
  specific-work-get:
    handler: api/payroll-setting/get_specific_work.get
    events:
      - http:
          path: specific-work/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: true
  specific-by-type-get:
    handler: api/payroll-setting/get_specific_by_type.get
    events:
      - http:
          path: specific-by-type/institute/{institute_id}/list/{id}
          method: GET
          cors: true
          request:
            parameters:
              paths:
                id: true