service: entity-payroll-settings

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  releasedVersion: v1
  stackName: ${self:service}-${self:custom.stage}
  region: ap-southeast-1 # this is the region that we deploy our lambda to
  deploymentBucket:
    blockPublicAccess: true # com.serverless.${opt:region, self:provider.region}.deploy
    name: com.serverless.ap-southeast-1.deploy
    versioning: false
  environment:
    item_table: Entity-${self:custom.stage}
  iamRoleStatements:
    - Effect: "Allow" # or Deny
      Resource: "*"
      Action: # this is the action against dynamodb
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
        - "dynamodb:BatchWriteItem"
        - "dynamodb:TransactWrite"
    - Effect: "Allow"
      Resource: "*"
      Action:
        - "sns:*"
plugins:
  - serverless-domain-manager
custom:
  stage: ${opt:stage, self:provider.stage}
  domains:
    prod: apis.banhji.com
    staging: staging-apis.banhji.com
    dev: dev-apis.banhji.com
  customDomain:
    basePath: ${self:service}
    domainName: ${self:custom.domains.${self:custom.stage}}
    stage: ${opt:stage, self:provider.stage}
    certificateName: '*.banhji.com'
    createRout53Record: true
package:
  individually: true
  patterns:
    - "!**/*"
functions:
  payroll-bank-create:
    handler: api/payroll-setting/add_bank.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/add_bank.js
      individually: true
    events:
      - http:
          path: bank/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-bank-get:
    handler: api/payroll-setting/get_bank.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/get_bank.js
      individually: true
    events:
      - http:
          path: bank/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-tax-create:
    handler: api/payroll-setting/add_tax.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/add_tax.js
      individually: true
    events:
      - http:
          path: tax/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-tax-get:
    handler: api/payroll-setting/get_tax.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/get_tax.js
      individually: true
    events:
      - http:
          path: tax/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-department-create:
    handler: api/payroll-setting/add_department.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/add_department.js
      individually: true
    events:
      - http:
          path: department/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-department-get:
    handler: api/payroll-setting/get_department.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/get_department.js
      individually: true
    events:
      - http:
          path: department/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-position-create:
    handler: api/payroll-setting/add_position.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/add_position.js
      individually: true
    events:
      - http:
          path: position/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-position-get:
    handler: api/payroll-setting/get_position.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/get_position.js
      individually: true
    events:
      - http:
          path: position/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-conponent-create:
    handler: api/payroll-setting/add_pay_component.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/add_pay_component.js
      individually: true
    events:
      - http:
          path: pay-component/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-conponent-get:
    handler: api/payroll-setting/get_pay_component.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/get_pay_component.js
      individually: true
    events:
      - http:
          path: pay-component/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-period-create:
    handler: api/payroll-setting/add_period.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/add_period.js
      individually: true
    events:
      - http:
          path: period/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-period-get:
    handler: api/payroll-setting/get_period.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/get_period.js
      individually: true
    events:
      - http:
          path: period/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-nssf-create:
    handler: api/payroll-setting/add_nssf.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/add_nssf.js
      individually: true
    events:
      - http:
          path: nssf/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  payroll-nssf-get:
    handler: api/payroll-setting/get_nssf.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/get_nssf.js
      individually: true
    events:
      - http:
          path: nssf/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  type-of-work-create:
    handler: api/payroll-setting/add_type_of_work.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/add_type_of_work.js
      individually: true
    events:
      - http:
          path: type-of-work/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  type-of-work-get:
    handler: api/payroll-setting/get_type_of_work.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/get_type_of_work.js
      individually: true
    events:
      - http:
          path: type-of-work/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  specific-work-create:
    handler: api/payroll-setting/add_specific_work.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/add_specific_work.js
      individually: true
    events:
      - http:
          path: specific-work/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  specific-work-get:
    handler: api/payroll-setting/get_specific_work.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/get_specific_work.js
      individually: true
    events:
      - http:
          path: specific-work/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  specific-by-type-get:
    handler: api/payroll-setting/get_specific_by_type.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/get_specific_by_type.js
      individually: true
    events:
      - http:
          path: specific-by-type/institute/{institute_id}/list/{id}
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
                id: true
  leave-get:
    handler: api/payroll-setting/get_leave.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/get_leave.js
      individually: true
    events:
      - http:
          path: leave/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  leave-post:
    handler: api/payroll-setting/add_leave.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/add_leave.js
      individually: true
    events:
      - http:
          path: leave/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  prefix-post:
    handler: api/payroll-setting/add_prefix.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/add_prefix.js
      individually: true
    events:
      - http:
          path: payroll-prefix/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  prefix-get:
    handler: api/payroll-setting/get_prefix.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/get_prefix.js
      individually: true
    events:
      - http:
          path: payroll-prefix/institute/{institute_id}/list
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  group-get:
    handler: api/payroll-setting/group.get
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/group.js
      individually: true
    events:
      - http:
          path: group-employee/institute/{institute_id}/get
          method: GET
          cors: true
          request:
            parameters:
              paths:
                institute_id: true
  group-create:
    handler: api/payroll-setting/group.index
    package:
      patterns:
        - config/**
        - node_modules/uuid/**
        - api/payroll-setting/group.js
      individually: true
    events:
      - http:
          path: group-employee/institute/{institute_id}/add
          method: POST
          cors: true
          request:
            parameters:
              paths:
                institute_id: true